env:
  browser: true
  es2021: true
  commonjs: true

extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaFeatures:
      jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
